/**:
  ros__parameters:
    plan_hz: 20
    tracking_dist: 3.0
    tolerance_d: 0.5
    tracking_dur: 3.0
    tracking_dt: 0.2
    theta_clearance: 0.8
    debug: false
    fake: true
    drone_id: 0
    prediction:
      rho_a: 1.0
      vmax: 4.0

