/**:
  ros__parameters:
    g: 9.81
    mass: 1.0
    Ixx: 0.0049
    Iyy: 0.0049
    Izz: 0.0088
    kf: 1.0e-6
    prop_radius: 0.10
    arm_length: 0.20
    motor_time_constant: 0.02
    max_rpm: 25000.0
    min_rpm: 0.0
    simulation_rate: 1000
    odom_rate: 400
    world_frame: world
    body_frame: body

