/**:
  ros__parameters:
    mass: 1.0
    g: 9.81
    frame_id: world
    gains:
      rot:
        x: 1.0
        y: 1.0
        z: 1.0
      ang:
        x: 0.1
        y: 0.1
        z: 0.1
    corrections:
      z: 0.0
      r: 0.0
      p: 0.0
    enable_motors: true
    use_external_yaw: false

